# Generated by Django 6.0.4 on 2026-04-21 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0017_listing_expires_at_listing_hoa_fee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('source', models.CharField(choices=[('inquiry', 'Listing Inquiry'), ('guided_search', 'Guided Search'), ('chat', 'Chat'), ('manual', 'Manual Entry')], default='inquiry', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('shortlist_ready', 'Shortlist Ready'), ('shortlist_sent', 'Shortlist Sent'), ('touring', 'Touring'), ('application_in_progress', 'Application In Progress'), ('closed_won', 'Closed / Won'), ('closed_lost', 'Closed / Lost')], default='new', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, help_text='Listing that triggered this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='listings.listing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('property_type', models.CharField(blank=True, max_length=20)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('amenities', models.CharField(blank=True, help_text='Comma-separated preferred amenities', max_length=500)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='portal.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlists', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlists', to='portal.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShortlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_note', models.TextField(blank=True)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('client_response', models.CharField(blank=True, choices=[('interested', 'Interested'), ('rejected', 'Rejected')], max_length=10, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlist_items', to='listings.listing')),
                ('shortlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portal.shortlist')),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
    ]
