# Generated by Django 6.0.4 on 2026-04-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadpreference',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='leadpreference',
            name='priority',
            field=models.CharField(blank=True, help_text='price | location | features', max_length=20),
        ),
        migrations.AddField(
            model_name='leadpreference',
            name='urgency',
            field=models.CharField(blank=True, help_text='just_looking | no_hurry | flexible | asap', max_length=20),
        ),
    ]
