# Generated by Django 6.0.4 on 2026-04-26 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_userlistingevent_community_and_more'),
        ('portal', '0002_add_priority_urgency_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='community',
            field=models.ForeignKey(blank=True, help_text='Community that triggered this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='listings.community'),
        ),
    ]
