# Generated by Django 5.2.13 on 2026-04-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_expand_listing_marketplace_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Comma-separated tags, e.g. pet-friendly, parking, furnished', max_length=200),
        ),
    ]
