# Generated by Django 5.2.13 on 2026-04-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_add_tags_to_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('roommates', 'Roommates'), ('rentals', 'Rentals'), ('properties', 'Properties'), ('local_services', 'Local Services'), ('jobs', 'Jobs'), ('buy_sell', 'Buy & Sell'), ('events', 'Events')], default='', max_length=32),
        ),
    ]
