# Generated by Django 5.2.13 on 2026-04-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_add_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price_unit',
            field=models.CharField(blank=True, choices=[('', '— select —'), ('mo', '/Month'), ('wk', '/Week'), ('day', '/Day'), ('hr', '/Hour')], default='', max_length=8),
        ),
    ]
