# Generated by Django 5.2.13 on 2026-04-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='available_from',
            field=models.DateField(blank=True, help_text='Date the listing becomes available (leave blank if available now)', null=True),
        ),
    ]
