# Generated by Django 5.2.13 on 2026-04-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_rental_detail_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Comma-separated tags, e.g. pet-friendly, parking, furnished', max_length=1000),
        ),
    ]
