# Generated by Django 5.2.13 on 2026-04-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_increase_tags_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityWaitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('email', 'city')},
            },
        ),
    ]
