# Generated by Django 5.2.13 on 2026-04-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_add_city_waitlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='address_line',
            field=models.CharField(blank=True, default='', help_text='Street address, e.g. 4521 Maple Ave', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
