# Generated by Django 5.2.13 on 2026-04-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_add_address_line_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('condo', 'Condo'), ('house', 'House'), ('townhouse', 'Townhouse'), ('basement', 'Basement'), ('loft', 'Loft'), ('studio', 'Studio'), ('trailer', 'Trailer'), ('single_family', 'Single-Family Home'), ('ranch_house', 'Ranch House'), ('land', 'Land'), ('ranch', 'Ranch')], default='', max_length=20),
        ),
    ]
