# Generated by Django 5.2.13 on 2026-04-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_add_listing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
