# Generated by Django 5.2.13 on 2026-04-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_add_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidedSearchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('start', 'Start'), ('complete', 'Complete')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of bedrooms (leave blank if not applicable)', null=True),
        ),
    ]
