# Generated by Django 6.0.4 on 2026-04-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_add_bedrooms_guided_search_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='expires_at',
            field=models.DateField(blank=True, help_text='Listing auto-expires on this date (leave blank for no expiry)', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='hoa_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original asking price — used to show Price Reduced badge', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='source_type',
            field=models.CharField(choices=[('native', 'Native'), ('mls_ntreis', 'NTREIS MLS')], default='native', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='square_footage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='year_built',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('pending', 'Pending Review'), ('flagged', 'Flagged'), ('under_contract', 'Under Contract'), ('sold', 'Sold')], default='pending', max_length=20),
        ),
    ]
