# Generated by Django 5.2.13 on 2026-04-26 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_listinginquiry_is_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserListingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', max_length=40)),
                ('event_type', models.CharField(choices=[('impression', 'Impression'), ('click', 'Click'), ('save', 'Save'), ('unsave', 'Unsave'), ('contact', 'Contact'), ('reject', 'Reject'), ('tour_request', 'Tour Request')], max_length=20)),
                ('label', models.SmallIntegerField(default=0)),
                ('search_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('rank_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fmm_score', models.FloatField(blank=True, null=True)),
                ('user_features_snapshot', models.JSONField(default=dict)),
                ('listing_features_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='listings.listing')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Listing Event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'listing', 'event_type'], name='listings_us_user_id_204810_idx'), models.Index(fields=['session_key', 'listing'], name='listings_us_session_166dce_idx')],
            },
        ),
    ]
