# Generated by Django 5.2.13 on 2026-04-26 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_add_user_listing_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='listings.listing'),
        ),
    ]
