# Generated by Django 5.2.13 on 2026-04-26 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_add_listing_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='parent',
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('address_line', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('community_amenities', models.CharField(blank=True, help_text='Comma-separated: Pool, Gym, Dog Park, Rooftop', max_length=2000)),
                ('in_unit_amenities', models.CharField(blank=True, help_text='Comma-separated: Washer/Dryer, Dishwasher, Balcony', max_length=2000)),
                ('pet_policy', models.CharField(blank=True, max_length=500)),
                ('parking_info', models.CharField(blank=True, max_length=500)),
                ('utilities_included', models.CharField(blank=True, max_length=500)),
                ('lease_terms', models.CharField(blank=True, max_length=200)),
                ('special_offer', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'communities',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='community_images/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.community')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "The Magnolia" or "2BR Classic"', max_length=80)),
                ('bedrooms', models.PositiveSmallIntegerField(default=1)),
                ('bathrooms', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('square_footage', models.PositiveIntegerField(blank=True, null=True)),
                ('floor_plan_image', models.ImageField(blank=True, null=True, upload_to='floor_plan_images/')),
                ('description', models.TextField(blank=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='listings.community')),
            ],
            options={
                'ordering': ['bedrooms', 'square_footage'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=20)),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('coming_soon', 'Coming Soon')], default='available', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('floor_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='listings.floorplan')),
            ],
            options={
                'ordering': ['unit_number'],
            },
        ),
    ]
