# Generated by Django 6.0.4 on 2026-04-26 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_community_floor_plan_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='floor_plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='floor_plan_images/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_community',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='virtual_tour_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
