# Generated by Django 6.0.4 on 2026-04-26 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_add_community_unit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='listings.listing'),
        ),
    ]
