# Generated by Django 6.0.4 on 2026-04-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_listing_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='community_type',
            field=models.CharField(blank=True, choices=[('apartment_complex', 'Apartment Complex'), ('condo_building', 'Condo Building'), ('townhouse_complex', 'Townhouse Complex'), ('mixed_use', 'Mixed Use'), ('student_housing', 'Student Housing'), ('senior_living', 'Senior Living'), ('other', 'Other')], default='', max_length=30),
        ),
    ]
