# Generated by Django 6.0.4 on 2026-04-26 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_add_community_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userlistingevent',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='listings.community'),
        ),
        migrations.AlterField(
            model_name='userlistingevent',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='listings.listing'),
        ),
        migrations.AddIndex(
            model_name='userlistingevent',
            index=models.Index(fields=['user', 'community', 'event_type'], name='listings_us_user_id_ad4f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='userlistingevent',
            index=models.Index(fields=['session_key', 'community'], name='listings_us_session_7b7ece_idx'),
        ),
    ]
