# Generated by Django 6.0.4 on 2026-04-27 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_userlistingevent_community_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(choices=[('rent', 'Rent'), ('buy', 'Buy')], max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('property_type', models.CharField(blank=True, max_length=20)),
                ('accommodation_type', models.CharField(blank=True, max_length=20)),
                ('amenities', models.CharField(blank=True, help_text='Comma-separated tags from guided search', max_length=500)),
                ('available_by', models.CharField(blank=True, max_length=20)),
                ('priority', models.CharField(blank=True, max_length=20)),
                ('urgency', models.CharField(blank=True, max_length=20)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'search_type')},
            },
        ),
    ]
