# Generated by Django 5.2.13 on 2026-04-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_add_saved_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='source_type',
            field=models.CharField(choices=[('native', 'Native'), ('mls_ntreis', 'NTREIS MLS'), ('realty_mole', 'Realty Mole')], default='native', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('on_hold', 'On Hold'), ('closed', 'Closed'), ('pending', 'Pending Review'), ('flagged', 'Flagged'), ('under_contract', 'Under Contract'), ('sold', 'Sold')], default='pending', max_length=20),
        ),
    ]
