# Generated by Django 5.2.13 on 2026-06-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_alter_listing_source_type_alter_listing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='geocoded_address',
            field=models.CharField(blank=True, default='', help_text='The address string last sent to the geocoder — used to detect changes', max_length=300),
        ),
        migrations.AddField(
            model_name='community',
            name='latitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='longitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='geocoded_address',
            field=models.CharField(blank=True, default='', help_text='The address string last sent to the geocoder — used to detect changes', max_length=300),
        ),
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
