# Generated by Django 5.2.13 on 2026-06-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_community_geocoded_address_community_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='alerts_enabled',
            field=models.BooleanField(default=True, help_text='Send new-match alerts (email/SMS) for this search'),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='last_alerted_at',
            field=models.DateTimeField(blank=True, help_text='Watermark — only listings created after this are alerted', null=True),
        ),
    ]
