# Generated by Django 5.2.13 on 2026-07-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_savedsearch_alerts_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bike_description',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='listing',
            name='bike_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='transit_description',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='listing',
            name='transit_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='walk_score',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='walk_score_description',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='listing',
            name='walk_score_link',
            field=models.URLField(blank=True, default='', help_text='Attribution link back to Walk Score — required by their API terms', max_length=500),
        ),
        migrations.AddField(
            model_name='listing',
            name='walk_score_updated',
            field=models.DateTimeField(blank=True, help_text='When the scores were last fetched — used to detect staleness', null=True),
        ),
    ]
