# Generated by Django 5.2.13 on 2026-08-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_listing_bike_description_listing_bike_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='source_type',
            field=models.CharField(choices=[('native', 'Native'), ('mls_ntreis', 'NTREIS MLS')], default='native', max_length=20),
        ),
    ]
