# Generated by Django 5.2.13 on 2026-08-11 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0031_alter_listing_source_type'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities', to='partners.organization'),
        ),
        migrations.AddField(
            model_name='community',
            name='media_rights_confirmed',
            field=models.BooleanField(default=False, help_text='Partner has authorized Listojo to display this media.'),
        ),
        migrations.AddField(
            model_name='listing',
            name='deactivation_pending_since',
            field=models.DateTimeField(blank=True, help_text='Set when a partner feed first omitted this row.', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='partners.organization'),
        ),
        migrations.AddField(
            model_name='listing',
            name='source_listing_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text="The partner's own ID for this unit. Blank for native listings.", max_length=120),
        ),
        migrations.AddField(
            model_name='unit',
            name='deactivation_pending_since',
            field=models.DateTimeField(blank=True, help_text='Set when a partner feed first omitted this unit.', null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='source_unit_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text="The partner's own ID for this unit. Defaults to unit_number.", max_length=120),
        ),
        migrations.AlterField(
            model_name='listing',
            name='source_type',
            field=models.CharField(choices=[('native', 'Native'), ('mls_ntreis', 'NTREIS MLS'), ('partner_csv', 'Partner CSV')], default='native', max_length=20),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('coming_soon', 'Coming Soon'), ('withdrawn', 'Withdrawn')], default='available', max_length=20),
        ),
    ]
