# Generated by Django 5.2.13 on 2026-08-19 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0033_alter_community_owner_alter_listing_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gs_id', models.CharField(help_text='GreatSchools universal-id — the identity we re-import against', max_length=40, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('school_type', models.CharField(blank=True, default='', help_text='public / private / charter, as reported by GreatSchools', max_length=20)),
                ('grade_range', models.CharField(blank=True, default='', max_length=40)),
                ('level_codes', models.CharField(blank=True, default='', help_text="Comma-separated GreatSchools level codes, e.g. 'e,m'", max_length=20)),
                ('level_rank', models.PositiveSmallIntegerField(default=1, help_text='Sort key derived from level_codes — see LEVEL_META')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=50)),
                ('rating', models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Overall GreatSchools rating, 1-10', null=True)),
                ('test_score_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('college_readiness_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('student_progress_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('profile_url', models.URLField(blank=True, default='', help_text='Attribution link back to GreatSchools — required by their API terms', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['level_rank', 'name'],
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='schools_updated',
            field=models.DateTimeField(blank=True, help_text='When nearby schools were last fetched — used to detect staleness', null=True),
        ),
        migrations.CreateModel(
            name='ListingSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_miles', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_schools', to='listings.listing')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_links', to='listings.school')),
            ],
            options={
                'ordering': ['school__level_rank', 'distance_miles'],
                'constraints': [models.UniqueConstraint(fields=('listing', 'school'), name='uniq_listing_school')],
            },
        ),
    ]
