# Generated by Django 5.2.13 on 2026-08-19 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0034_school_listing_schools_updated_listingschool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downtown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name, e.g. 'Downtown Dallas'", max_length=120, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['state', 'city'],
            },
        ),
        migrations.CreateModel(
            name='GroceryStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=200, unique=True)),
                ('chain', models.CharField(db_index=True, max_length=60)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['chain', 'name'],
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='downtown_distance_miles',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='groceries_updated',
            field=models.DateTimeField(blank=True, help_text='When nearby groceries were last fetched — used to detect staleness', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='nearest_downtown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='listings.downtown'),
        ),
        migrations.CreateModel(
            name='ListingGroceryStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_miles', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_groceries', to='listings.listing')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_links', to='listings.grocerystore')),
            ],
            options={
                'ordering': ['distance_miles'],
                'constraints': [models.UniqueConstraint(fields=('listing', 'store'), name='uniq_listing_grocery_store')],
            },
        ),
    ]
