# Generated by Django 5.2.13 on 2026-08-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0036_rename_las_colinas_downtown'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='downtown_drive_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='drive_times_updated',
            field=models.DateTimeField(blank=True, help_text='When drive times were last fetched — used to detect staleness', null=True),
        ),
        migrations.AddField(
            model_name='listinggrocerystore',
            name='drive_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
