# Generated by Django 5.2.13 on 2026-08-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0037_listing_downtown_drive_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='downtown_drive_miles',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='listinggrocerystore',
            name='drive_miles',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
