# Generated by Django 5.2.13 on 2026-08-20 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0038_listing_downtown_drive_miles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Short identifier used on the import command, e.g. 'dart'", max_length=40, unique=True)),
                ('name', models.CharField(help_text="Badge name shown on the card, e.g. 'DART'", max_length=60)),
                ('full_name', models.CharField(blank=True, default='', help_text="Legal name from the feed, e.g. 'Dallas Area Rapid Transit'", max_length=160)),
                ('gtfs_url', models.URLField(help_text='Direct link to the agency GTFS zip', max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_imported', models.DateTimeField(blank=True, help_text='When this feed was last imported', null=True)),
                ('feed_version', models.CharField(blank=True, default='', max_length=120)),
            ],
            options={
                'verbose_name_plural': 'transit agencies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='commute_score',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='0-100 composite: rail access, network reach, frequent service, downtown drive', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='commute_score_label',
            field=models.CharField(blank=True, default='', help_text="Band name shown under the score, e.g. 'Excellent Transit'", max_length=40),
        ),
        migrations.AddField(
            model_name='listing',
            name='transit_updated',
            field=models.DateTimeField(blank=True, help_text='When nearby stations were last matched — used to detect staleness', null=True),
        ),
        migrations.CreateModel(
            name='TransitRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=120)),
                ('short_name', models.CharField(blank=True, default='', help_text="Badge text, e.g. 'RED' or '705'", max_length=60)),
                ('long_name', models.CharField(blank=True, default='', max_length=200)),
                ('mode', models.CharField(choices=[('commuter_rail', 'Commuter Rail'), ('subway', 'Subway'), ('light_rail', 'Light Rail'), ('streetcar', 'Streetcar'), ('bus', 'Bus')], db_index=True, max_length=20)),
                ('color', models.CharField(blank=True, default='', max_length=6)),
                ('text_color', models.CharField(blank=True, default='', max_length=6)),
                ('trips_per_weekday', models.PositiveIntegerField(default=0)),
                ('is_frequent', models.BooleanField(db_index=True, default=False, help_text='Runs often enough to be worth showing on its own')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='listings.transitagency')),
            ],
            options={
                'ordering': ['agency', 'mode', 'short_name'],
            },
        ),
        migrations.CreateModel(
            name='StationRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_links', to='listings.transitroute')),
            ],
        ),
        migrations.CreateModel(
            name='TransitStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('mode', models.CharField(choices=[('commuter_rail', 'Commuter Rail'), ('subway', 'Subway'), ('light_rail', 'Light Rail'), ('streetcar', 'Streetcar'), ('bus', 'Bus')], db_index=True, max_length=20)),
                ('is_rail', models.BooleanField(db_index=True, default=False)),
                ('trips_per_weekday', models.PositiveIntegerField(default=0, help_text='All modes, busiest weekday')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='listings.transitagency')),
                ('routes', models.ManyToManyField(related_name='stations', through='listings.StationRoute', to='listings.transitroute')),
            ],
            options={
                'ordering': ['agency', 'name'],
            },
        ),
        migrations.AddField(
            model_name='stationroute',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_links', to='listings.transitstation'),
        ),
        migrations.CreateModel(
            name='ListingTransitStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_miles', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('drive_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('drive_miles', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_transit', to='listings.listing')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_links', to='listings.transitstation')),
            ],
            options={
                'ordering': ['-station__is_rail', 'distance_miles'],
            },
        ),
        migrations.AddConstraint(
            model_name='transitroute',
            constraint=models.UniqueConstraint(fields=('agency', 'source_id'), name='uniq_agency_transit_route'),
        ),
        migrations.AddIndex(
            model_name='transitstation',
            index=models.Index(fields=['latitude', 'longitude'], name='transit_station_latlng'),
        ),
        migrations.AddConstraint(
            model_name='transitstation',
            constraint=models.UniqueConstraint(fields=('agency', 'source_id'), name='uniq_agency_transit_station'),
        ),
        migrations.AddConstraint(
            model_name='stationroute',
            constraint=models.UniqueConstraint(fields=('station', 'route'), name='uniq_station_transit_route'),
        ),
        migrations.AddConstraint(
            model_name='listingtransitstation',
            constraint=models.UniqueConstraint(fields=('listing', 'station'), name='uniq_listing_transit_station'),
        ),
    ]
