# Generated by Django 5.2.13 on 2026-08-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0040_community_media_rights_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityimage',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
