# Generated by Django 5.2.13 on 2026-08-28 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0041_communityimage_source_url_listingimage_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='bike_description',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='community',
            name='bike_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='commute_score',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='0-100 composite: rail access, network reach, frequent service, downtown drive', null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='commute_score_label',
            field=models.CharField(blank=True, default='', help_text="Band name shown under the score, e.g. 'Excellent Transit'", max_length=40),
        ),
        migrations.AddField(
            model_name='community',
            name='downtown_distance_miles',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='downtown_drive_miles',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='downtown_drive_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='drive_times_updated',
            field=models.DateTimeField(blank=True, help_text='When drive times were last fetched — used to detect staleness', null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='groceries_updated',
            field=models.DateTimeField(blank=True, help_text='When nearby groceries were last fetched — used to detect staleness', null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='nearest_downtown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities', to='listings.downtown'),
        ),
        migrations.AddField(
            model_name='community',
            name='transit_description',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='community',
            name='transit_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='transit_updated',
            field=models.DateTimeField(blank=True, help_text='When nearby stations were last matched — used to detect staleness', null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='walk_score',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='walk_score_description',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='community',
            name='walk_score_link',
            field=models.URLField(blank=True, default='', help_text='Attribution link back to Walk Score — required by their API terms', max_length=500),
        ),
        migrations.AddField(
            model_name='community',
            name='walk_score_updated',
            field=models.DateTimeField(blank=True, help_text='When the scores were last fetched — used to detect staleness', null=True),
        ),
        migrations.CreateModel(
            name='CommunityGroceryStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_miles', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('drive_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('drive_miles', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_groceries', to='listings.community')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_links', to='listings.grocerystore')),
            ],
            options={
                'ordering': ['distance_miles'],
                'constraints': [models.UniqueConstraint(fields=('community', 'store'), name='uniq_community_grocery_store')],
            },
        ),
        migrations.CreateModel(
            name='CommunityTransitStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_miles', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('drive_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('drive_miles', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_transit', to='listings.community')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_links', to='listings.transitstation')),
            ],
            options={
                'ordering': ['-station__is_rail', 'distance_miles'],
                'constraints': [models.UniqueConstraint(fields=('community', 'station'), name='uniq_community_transit_station')],
            },
        ),
    ]
