# Generated by Django 5.2.13 on 2026-08-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0042_community_bike_description_community_bike_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='community_amenities',
            field=models.CharField(blank=True, default='', help_text='Shared or outside your door, comma-separated: Pool, Gym, Dog Park, Gated Entry', max_length=2000),
        ),
        migrations.AddField(
            model_name='listing',
            name='in_unit_amenities',
            field=models.CharField(blank=True, default='', help_text='Yours alone, behind your door, comma-separated: Washer/Dryer, Dishwasher, Balcony', max_length=2000),
        ),
    ]
