# Generated by Django 5.2.17 on 2026-09-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0043_listing_community_amenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listinginquiry',
            name='fit_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
