# Generated by Django 5.2.13 on 2026-08-11 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_assistedonboardingrequest_importrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=160)),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('website', models.URLField(blank=True, default='')),
                ('portfolio_size', models.CharField(blank=True, choices=[('1-25', '1–25 units'), ('26-100', '26–100 units'), ('101-500', '101–500 units'), ('500+', '500+ units')], default='', max_length=20)),
                ('markets', models.CharField(blank=True, default='', help_text='Cities or submarkets, e.g. Dallas, Plano, Frisco', max_length=200)),
                ('pms_name', models.CharField(blank=True, default='', help_text='RealPage, Yardi, Entrata, AppFolio, other, or unknown', max_length=80)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('approved', 'Approved'), ('declined', 'Declined')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='partners.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
