# Generated by Django 5.2.13 on 2026-08-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='signup_intent',
            field=models.CharField(blank=True, choices=[('renter', 'Looking for a place'), ('landlord', 'Listing a place')], default='', max_length=20),
        ),
    ]
