# Generated by Django 5.2.13 on 2026-04-11 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_guestchatmessage_guest_session_key'),
        ('listings', '0002_expand_listing_marketplace_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='listings.listing'),
        ),
    ]
